"""initial schema

Revision ID: c3180cc71007
Revises: 
Create Date: 2026-07-27 03:03:52.743813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import reviewpulse.db.models  # custom column types (UtcDateTime)


# revision identifiers, used by Alembic.
revision: str = 'c3180cc71007'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_message_id', sa.Integer(), nullable=False),
    sa.Column('discussion_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('discussion_message_id', sa.Integer(), nullable=True),
    sa.Column('card_message_id', sa.Integer(), nullable=True),
    sa.Column('author_user_id', sa.BigInteger(), nullable=True),
    sa.Column('author_label', sa.String(length=256), nullable=True),
    sa.Column('product', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('task_url', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('posted_at', reviewpulse.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('closed_at', reviewpulse.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', reviewpulse.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', reviewpulse.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_chat_id', 'channel_message_id', name='uq_review_channel_msg')
    )
    op.create_index(op.f('ix_reviews_author_user_id'), 'reviews', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_reviews_channel_chat_id'), 'reviews', ['channel_chat_id'], unique=False)
    op.create_index(op.f('ix_reviews_is_closed'), 'reviews', ['is_closed'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('gitlab_username', sa.String(length=128), nullable=True),
    sa.Column('can_be_dmed', sa.Boolean(), nullable=False),
    sa.Column('muted_until', reviewpulse.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', reviewpulse.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', reviewpulse.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_gitlab_username'), 'users', ['gitlab_username'], unique=False)
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('merge_request_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=256), nullable=False),
    sa.Column('project_path', sa.String(length=512), nullable=False),
    sa.Column('iid', sa.Integer(), nullable=False),
    sa.Column('blocking_discussions_resolved', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', reviewpulse.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'project_path', 'iid', name='uq_mr_per_review')
    )
    op.create_index(op.f('ix_merge_request_links_review_id'), 'merge_request_links', ['review_id'], unique=False)
    op.create_table('reviewer_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('mention_key', sa.String(length=96), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('display_label', sa.String(length=128), nullable=False),
    sa.Column('state', sa.Enum('pending', 'changes_requested', 'awaiting_recheck', 'approved', name='reviewer_state', native_enum=False, length=32), nullable=False),
    sa.Column('ball_since', reviewpulse.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('decided_at', reviewpulse.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_nudge_at', reviewpulse.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('nudges_today', sa.Integer(), nullable=False),
    sa.Column('snoozed_until', reviewpulse.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('registration_hint_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', reviewpulse.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', reviewpulse.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'mention_key', name='uq_assignment_per_review')
    )
    op.create_index('ix_assignment_open', 'reviewer_assignments', ['state', 'review_id'], unique=False)
    op.create_index(op.f('ix_reviewer_assignments_review_id'), 'reviewer_assignments', ['review_id'], unique=False)
    op.create_index(op.f('ix_reviewer_assignments_state'), 'reviewer_assignments', ['state'], unique=False)
    op.create_index(op.f('ix_reviewer_assignments_telegram_user_id'), 'reviewer_assignments', ['telegram_user_id'], unique=False)
    op.create_index(op.f('ix_reviewer_assignments_username'), 'reviewer_assignments', ['username'], unique=False)
    op.create_table('nudge_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('sent_at', reviewpulse.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['reviewer_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nudge_log_assignment_id'), 'nudge_log', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_nudge_log_sent_at'), 'nudge_log', ['sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nudge_log_sent_at'), table_name='nudge_log')
    op.drop_index(op.f('ix_nudge_log_assignment_id'), table_name='nudge_log')
    op.drop_table('nudge_log')
    op.drop_index(op.f('ix_reviewer_assignments_username'), table_name='reviewer_assignments')
    op.drop_index(op.f('ix_reviewer_assignments_telegram_user_id'), table_name='reviewer_assignments')
    op.drop_index(op.f('ix_reviewer_assignments_state'), table_name='reviewer_assignments')
    op.drop_index(op.f('ix_reviewer_assignments_review_id'), table_name='reviewer_assignments')
    op.drop_index('ix_assignment_open', table_name='reviewer_assignments')
    op.drop_table('reviewer_assignments')
    op.drop_index(op.f('ix_merge_request_links_review_id'), table_name='merge_request_links')
    op.drop_table('merge_request_links')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_gitlab_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reviews_is_closed'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_channel_chat_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_author_user_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
